# ===========================================================================
# Chronos AI Learning Companion
# File: schemas/plan_schema.py
# Purpose: Plan proposal Pydantic model for Principal generation
# ===========================================================================

"""
Plan Proposal Schema

Structured output from Principal, generated by Gemini 3.
Every "why" must reference evidence (SQLite or ReMe).
"""

from pydantic import BaseModel, Field
from typing import List, Optional


class PlanItem(BaseModel):
    """Single item in a learning plan."""
    time: str = Field(..., description="Scheduled time (HH:MM)")
    duration: int = Field(default=25, ge=5, le=120, description="Duration in minutes")
    topic: str = Field(..., description="Topic or activity name")
    type: str = Field(default="study", description="Type: study/practice/review/break")
    concept_id: Optional[str] = Field(default=None, description="Linked concept ID if any")


class PlanDiff(BaseModel):
    """Changes from previous plan."""
    added: List[str] = Field(default_factory=list, description="Newly added items")
    removed: List[str] = Field(default_factory=list, description="Removed items")
    modified: List[str] = Field(default_factory=list, description="Modified items")
    reason: str = Field(default="", description="Main reason for changes")


class WhyItem(BaseModel):
    """
    Single rationale with traceable evidence.
    
    Must have either evidence_id (SQLite) or reme_memory_id (ReMe).
    """
    text: str = Field(..., description="Human-readable explanation")
    evidence_id: Optional[str] = Field(default=None, description="SQLite evidence ID")
    reme_memory_id: Optional[str] = Field(default=None, description="ReMe memory ID")
    
    def has_evidence(self) -> bool:
        """Check if this why item has traceable evidence."""
        return bool(self.evidence_id or self.reme_memory_id)


class PlanProposal(BaseModel):
    """
    Complete plan proposal from Principal.
    
    Generated by Gemini 3 using:
    - User profile from SQLite
    - Recent receipts from SQLite
    - Mastery data from SQLite
    - Personal memory from ReMe
    - Task memory from ReMe (optional)
    """
    date: str = Field(..., description="Plan date (YYYY-MM-DD)")
    plan: List[PlanItem] = Field(
        default_factory=list,
        description="Ordered list of plan items"
    )
    diff: PlanDiff = Field(
        default_factory=PlanDiff,
        description="Changes from previous plan"
    )
    why: List[WhyItem] = Field(
        default_factory=list,
        description="Rationale with evidence references"
    )
    briefing_questions: List[str] = Field(
        default_factory=list,
        description="Questions to ask user during briefing"
    )
    mode: str = Field(
        default="standard",
        description="Recommended mode: recovery/standard/sprint"
    )
    
    def all_why_have_evidence(self) -> bool:
        """Validate all why items have evidence."""
        return all(w.has_evidence() for w in self.why)
    
    class Config:
        json_schema_extra = {
            "example": {
                "date": "2026-01-14",
                "plan": [
                    {"time": "09:00", "duration": 25, "topic": "Recursion Practice", "type": "practice"},
                    {"time": "09:30", "duration": 10, "topic": "Break", "type": "break"},
                    {"time": "09:40", "duration": 25, "topic": "Tree Basics", "type": "study"}
                ],
                "diff": {
                    "added": ["Recursion Practice"],
                    "removed": ["New Topic: Graphs"],
                    "modified": [],
                    "reason": "Yesterday's stuck point on recursion needs reinforcement"
                },
                "why": [
                    {"text": "Recursion mastery is 0.6, below threshold", "evidence_id": "ev-123"},
                    {"text": "User prefers morning practice sessions", "reme_memory_id": "rm-456"}
                ],
                "briefing_questions": ["Accept this recovery-focused plan?"],
                "mode": "recovery"
            }
        }


# =============================================================================
# Gemini Generation Prompt
# =============================================================================

PLAN_GENERATION_PROMPT = """You are the Principal of Chronos, an AI learning companion.

Generate a learning plan for {date} based on:

USER PROFILE:
{user_profile}

RECENT EXECUTION RECEIPTS:
{receipts}

MASTERY DATA:
{mastery}

PERSONAL MEMORY (from ReMe):
{personal_memory}

TASK MEMORY (strategies, optional):
{task_memory}

REQUIREMENTS:
1. Create a realistic daily learning plan (plan items with time, duration, topic, type)
2. Explain what changed and why (diff)
3. For EVERY "why" item, you MUST reference either:
   - An evidence_id from receipts/mastery shown above
   - A reme_memory_id from personal/task memory shown above
4. Suggest a mode (recovery/standard/sprint) based on learner state
5. Add 1-2 briefing questions for user confirmation

Return ONLY valid JSON matching the PlanProposal schema."""
